# Generated by Django 6.0.7 on 2026-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='todo_images/'),
        ),
    ]
